esphome:
  name: enermon_example
  platform: ESP32
  board: esp32dev

external_components:
  - source: https://github.com/makusets/enermon
    components: [enermon]

wifi:
  ssid: "Your_SSID"
  password: "Your_PASSWORD"

logger:

api:

ota:

sensor:
  - platform: enermon
    id: enermon_sensor
    ct_names: ["solar","ac","grid","load"]
    ct_pins: [34,35,32,33]
    ct_cal: [1111.0, 1111.0, 1111.0, 1111.0]     # tune per CT with known load
    voltage_pin: 39
    voltage_cal: 230.0
    voltage_phase: 1.7
    sample_count: 200



status_led:
  pin: GPIO2